#!/bin/bash

set -e

echo "Creating links..."

scripts_to_link=(webcam-enable webcam-disable webcam-status webcam-set-default)

for script in ${scripts_to_link[@]}; do
    if [ -f /usr/bin/$script ]; then 
        rm /usr/bin/$script
    fi
    ln -s /usr/share/webcam-utils/$script.sh /usr/bin/$script
done

echo "Successfully created links."

#DEBHELPER#

exit 0
